# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: sls-express-app

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

# The `functions` block defines what code to deploy
functions:
  app:
    handler: index.handler
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http: ANY /
          cors: true
      -http: 'ANY {proxy+}'
